//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 inherent.design <mannie@inherent.design>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplication) DeepCopyInto(out *AccessApplication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplication.
func (in *AccessApplication) DeepCopy() *AccessApplication {
	if in == nil {
		return nil
	}
	out := new(AccessApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessCountryRule) DeepCopyInto(out *AccessCountryRule) {
	*out = *in
	if in.Codes != nil {
		in, out := &in.Codes, &out.Codes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessCountryRule.
func (in *AccessCountryRule) DeepCopy() *AccessCountryRule {
	if in == nil {
		return nil
	}
	out := new(AccessCountryRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEmailDomainRule) DeepCopyInto(out *AccessEmailDomainRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEmailDomainRule.
func (in *AccessEmailDomainRule) DeepCopy() *AccessEmailDomainRule {
	if in == nil {
		return nil
	}
	out := new(AccessEmailDomainRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEmailListRule) DeepCopyInto(out *AccessEmailListRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEmailListRule.
func (in *AccessEmailListRule) DeepCopy() *AccessEmailListRule {
	if in == nil {
		return nil
	}
	out := new(AccessEmailListRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEmailRule) DeepCopyInto(out *AccessEmailRule) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEmailRule.
func (in *AccessEmailRule) DeepCopy() *AccessEmailRule {
	if in == nil {
		return nil
	}
	out := new(AccessEmailRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGSuiteGroupRule) DeepCopyInto(out *AccessGSuiteGroupRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGSuiteGroupRule.
func (in *AccessGSuiteGroupRule) DeepCopy() *AccessGSuiteGroupRule {
	if in == nil {
		return nil
	}
	out := new(AccessGSuiteGroupRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupRef) DeepCopyInto(out *AccessGroupRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupRef.
func (in *AccessGroupRef) DeepCopy() *AccessGroupRef {
	if in == nil {
		return nil
	}
	out := new(AccessGroupRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIPListRule) DeepCopyInto(out *AccessIPListRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIPListRule.
func (in *AccessIPListRule) DeepCopy() *AccessIPListRule {
	if in == nil {
		return nil
	}
	out := new(AccessIPListRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIPRule) DeepCopyInto(out *AccessIPRule) {
	*out = *in
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIPRule.
func (in *AccessIPRule) DeepCopy() *AccessIPRule {
	if in == nil {
		return nil
	}
	out := new(AccessIPRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessOIDCClaimRule) DeepCopyInto(out *AccessOIDCClaimRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessOIDCClaimRule.
func (in *AccessOIDCClaimRule) DeepCopy() *AccessOIDCClaimRule {
	if in == nil {
		return nil
	}
	out := new(AccessOIDCClaimRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyRule) DeepCopyInto(out *AccessPolicyRule) {
	*out = *in
	if in.Precedence != nil {
		in, out := &in.Precedence, &out.Precedence
		*out = new(int)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]AccessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]AccessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = make([]AccessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApprovalGroups != nil {
		in, out := &in.ApprovalGroups, &out.ApprovalGroups
		*out = make([]ApprovalGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyRule.
func (in *AccessPolicyRule) DeepCopy() *AccessPolicyRule {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessRule) DeepCopyInto(out *AccessRule) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(AccessIPRule)
		(*in).DeepCopyInto(*out)
	}
	if in.IPList != nil {
		in, out := &in.IPList, &out.IPList
		*out = new(AccessIPListRule)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(AccessCountryRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Everyone != nil {
		in, out := &in.Everyone, &out.Everyone
		*out = new(bool)
		**out = **in
	}
	if in.ServiceToken != nil {
		in, out := &in.ServiceToken, &out.ServiceToken
		*out = new(AccessServiceTokenRule)
		**out = **in
	}
	if in.AnyValidServiceToken != nil {
		in, out := &in.AnyValidServiceToken, &out.AnyValidServiceToken
		*out = new(bool)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(AccessEmailRule)
		(*in).DeepCopyInto(*out)
	}
	if in.EmailList != nil {
		in, out := &in.EmailList, &out.EmailList
		*out = new(AccessEmailListRule)
		**out = **in
	}
	if in.EmailDomain != nil {
		in, out := &in.EmailDomain, &out.EmailDomain
		*out = new(AccessEmailDomainRule)
		**out = **in
	}
	if in.OIDCClaim != nil {
		in, out := &in.OIDCClaim, &out.OIDCClaim
		*out = new(AccessOIDCClaimRule)
		**out = **in
	}
	if in.GSuiteGroup != nil {
		in, out := &in.GSuiteGroup, &out.GSuiteGroup
		*out = new(AccessGSuiteGroupRule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessRule.
func (in *AccessRule) DeepCopy() *AccessRule {
	if in == nil {
		return nil
	}
	out := new(AccessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessServiceTokenRule) DeepCopyInto(out *AccessServiceTokenRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessServiceTokenRule.
func (in *AccessServiceTokenRule) DeepCopy() *AccessServiceTokenRule {
	if in == nil {
		return nil
	}
	out := new(AccessServiceTokenRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalGroup) DeepCopyInto(out *ApprovalGroup) {
	*out = *in
	if in.Emails != nil {
		in, out := &in.Emails, &out.Emails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalGroup.
func (in *ApprovalGroup) DeepCopy() *ApprovalGroup {
	if in == nil {
		return nil
	}
	out := new(ApprovalGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPoolSecretRef) DeepCopyInto(out *CAPoolSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPoolSecretRef.
func (in *CAPoolSecretRef) DeepCopy() *CAPoolSecretRef {
	if in == nil {
		return nil
	}
	out := new(CAPoolSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CASecretRef) DeepCopyInto(out *CASecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CASecretRef.
func (in *CASecretRef) DeepCopy() *CASecretRef {
	if in == nil {
		return nil
	}
	out := new(CASecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicy) DeepCopyInto(out *CloudflareAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicy.
func (in *CloudflareAccessPolicy) DeepCopy() *CloudflareAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicyList) DeepCopyInto(out *CloudflareAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicyList.
func (in *CloudflareAccessPolicyList) DeepCopy() *CloudflareAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicySpec) DeepCopyInto(out *CloudflareAccessPolicySpec) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(PolicyTargetReference)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]PolicyTargetReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CloudflareRef != nil {
		in, out := &in.CloudflareRef, &out.CloudflareRef
		*out = new(CloudflareSecretRef)
		(*in).DeepCopyInto(*out)
	}
	out.Application = in.Application
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]AccessPolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupRefs != nil {
		in, out := &in.GroupRefs, &out.GroupRefs
		*out = make([]AccessGroupRef, len(*in))
		copy(*out, *in)
	}
	if in.ServiceTokens != nil {
		in, out := &in.ServiceTokens, &out.ServiceTokens
		*out = make([]ServiceTokenConfig, len(*in))
		copy(*out, *in)
	}
	if in.MTLS != nil {
		in, out := &in.MTLS, &out.MTLS
		*out = new(MTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicySpec.
func (in *CloudflareAccessPolicySpec) DeepCopy() *CloudflareAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicyStatus) DeepCopyInto(out *CloudflareAccessPolicyStatus) {
	*out = *in
	if in.ServiceTokenIDs != nil {
		in, out := &in.ServiceTokenIDs, &out.ServiceTokenIDs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ancestors != nil {
		in, out := &in.Ancestors, &out.Ancestors
		*out = make([]PolicyAncestorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicyStatus.
func (in *CloudflareAccessPolicyStatus) DeepCopy() *CloudflareAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareConfig) DeepCopyInto(out *CloudflareConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.SecretKeys = in.SecretKeys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareConfig.
func (in *CloudflareConfig) DeepCopy() *CloudflareConfig {
	if in == nil {
		return nil
	}
	out := new(CloudflareConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNS) DeepCopyInto(out *CloudflareDNS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNS.
func (in *CloudflareDNS) DeepCopy() *CloudflareDNS {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareDNS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSList) DeepCopyInto(out *CloudflareDNSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareDNS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSList.
func (in *CloudflareDNSList) DeepCopy() *CloudflareDNSList {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareDNSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSSpec) DeepCopyInto(out *CloudflareDNSSpec) {
	*out = *in
	if in.TunnelRef != nil {
		in, out := &in.TunnelRef, &out.TunnelRef
		*out = new(DNSTunnelRef)
		**out = **in
	}
	if in.ExternalTarget != nil {
		in, out := &in.ExternalTarget, &out.ExternalTarget
		*out = new(ExternalTarget)
		**out = **in
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]DNSZoneConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Source.DeepCopyInto(&out.Source)
	out.Defaults = in.Defaults
	in.Ownership.DeepCopyInto(&out.Ownership)
	in.CleanupPolicy.DeepCopyInto(&out.CleanupPolicy)
	if in.Cloudflare != nil {
		in, out := &in.Cloudflare, &out.Cloudflare
		*out = new(CloudflareConfig)
		**out = **in
	}
	if in.FallbackCredentialsRef != nil {
		in, out := &in.FallbackCredentialsRef, &out.FallbackCredentialsRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSSpec.
func (in *CloudflareDNSSpec) DeepCopy() *CloudflareDNSSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSStatus) DeepCopyInto(out *CloudflareDNSStatus) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]DNSRecordSyncStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSStatus.
func (in *CloudflareDNSStatus) DeepCopy() *CloudflareDNSStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareSecretRef) DeepCopyInto(out *CloudflareSecretRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareSecretRef.
func (in *CloudflareSecretRef) DeepCopy() *CloudflareSecretRef {
	if in == nil {
		return nil
	}
	out := new(CloudflareSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnel) DeepCopyInto(out *CloudflareTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnel.
func (in *CloudflareTunnel) DeepCopy() *CloudflareTunnel {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelList) DeepCopyInto(out *CloudflareTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelList.
func (in *CloudflareTunnelList) DeepCopy() *CloudflareTunnelList {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelSpec) DeepCopyInto(out *CloudflareTunnelSpec) {
	*out = *in
	out.Tunnel = in.Tunnel
	out.Cloudflare = in.Cloudflare
	in.Cloudflared.DeepCopyInto(&out.Cloudflared)
	in.OriginDefaults.DeepCopyInto(&out.OriginDefaults)
	if in.FallbackCredentialsRef != nil {
		in, out := &in.FallbackCredentialsRef, &out.FallbackCredentialsRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelSpec.
func (in *CloudflareTunnelSpec) DeepCopy() *CloudflareTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelStatus) DeepCopyInto(out *CloudflareTunnelStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelStatus.
func (in *CloudflareTunnelStatus) DeepCopy() *CloudflareTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflaredConfig) DeepCopyInto(out *CloudflaredConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Metrics = in.Metrics
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflaredConfig.
func (in *CloudflaredConfig) DeepCopy() *CloudflaredConfig {
	if in == nil {
		return nil
	}
	out := new(CloudflaredConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSCleanupPolicy) DeepCopyInto(out *DNSCleanupPolicy) {
	*out = *in
	if in.DeleteOnRouteRemoval != nil {
		in, out := &in.DeleteOnRouteRemoval, &out.DeleteOnRouteRemoval
		*out = new(bool)
		**out = **in
	}
	if in.DeleteOnResourceRemoval != nil {
		in, out := &in.DeleteOnResourceRemoval, &out.DeleteOnResourceRemoval
		*out = new(bool)
		**out = **in
	}
	if in.OnlyManaged != nil {
		in, out := &in.OnlyManaged, &out.OnlyManaged
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSCleanupPolicy.
func (in *DNSCleanupPolicy) DeepCopy() *DNSCleanupPolicy {
	if in == nil {
		return nil
	}
	out := new(DNSCleanupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSCommentOwnership) DeepCopyInto(out *DNSCommentOwnership) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSCommentOwnership.
func (in *DNSCommentOwnership) DeepCopy() *DNSCommentOwnership {
	if in == nil {
		return nil
	}
	out := new(DNSCommentOwnership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSExplicitHostname) DeepCopyInto(out *DNSExplicitHostname) {
	*out = *in
	if in.Proxied != nil {
		in, out := &in.Proxied, &out.Proxied
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSExplicitHostname.
func (in *DNSExplicitHostname) DeepCopy() *DNSExplicitHostname {
	if in == nil {
		return nil
	}
	out := new(DNSExplicitHostname)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSGatewayRoutesSource) DeepCopyInto(out *DNSGatewayRoutesSource) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(DNSNamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSGatewayRoutesSource.
func (in *DNSGatewayRoutesSource) DeepCopy() *DNSGatewayRoutesSource {
	if in == nil {
		return nil
	}
	out := new(DNSGatewayRoutesSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSHostnameSource) DeepCopyInto(out *DNSHostnameSource) {
	*out = *in
	in.GatewayRoutes.DeepCopyInto(&out.GatewayRoutes)
	if in.Explicit != nil {
		in, out := &in.Explicit, &out.Explicit
		*out = make([]DNSExplicitHostname, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSHostnameSource.
func (in *DNSHostnameSource) DeepCopy() *DNSHostnameSource {
	if in == nil {
		return nil
	}
	out := new(DNSHostnameSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSNamespaceSelector) DeepCopyInto(out *DNSNamespaceSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSNamespaceSelector.
func (in *DNSNamespaceSelector) DeepCopy() *DNSNamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(DNSNamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSOwnershipConfig) DeepCopyInto(out *DNSOwnershipConfig) {
	*out = *in
	in.TXTRecord.DeepCopyInto(&out.TXTRecord)
	out.Comment = in.Comment
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSOwnershipConfig.
func (in *DNSOwnershipConfig) DeepCopy() *DNSOwnershipConfig {
	if in == nil {
		return nil
	}
	out := new(DNSOwnershipConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordDefaults) DeepCopyInto(out *DNSRecordDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordDefaults.
func (in *DNSRecordDefaults) DeepCopy() *DNSRecordDefaults {
	if in == nil {
		return nil
	}
	out := new(DNSRecordDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSyncStatus) DeepCopyInto(out *DNSRecordSyncStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSyncStatus.
func (in *DNSRecordSyncStatus) DeepCopy() *DNSRecordSyncStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSTXTRecordOwnership) DeepCopyInto(out *DNSTXTRecordOwnership) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSTXTRecordOwnership.
func (in *DNSTXTRecordOwnership) DeepCopy() *DNSTXTRecordOwnership {
	if in == nil {
		return nil
	}
	out := new(DNSTXTRecordOwnership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSTunnelRef) DeepCopyInto(out *DNSTunnelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSTunnelRef.
func (in *DNSTunnelRef) DeepCopy() *DNSTunnelRef {
	if in == nil {
		return nil
	}
	out := new(DNSTunnelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneConfig) DeepCopyInto(out *DNSZoneConfig) {
	*out = *in
	if in.Proxied != nil {
		in, out := &in.Proxied, &out.Proxied
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneConfig.
func (in *DNSZoneConfig) DeepCopy() *DNSZoneConfig {
	if in == nil {
		return nil
	}
	out := new(DNSZoneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalTarget) DeepCopyInto(out *ExternalTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalTarget.
func (in *ExternalTarget) DeepCopy() *ExternalTarget {
	if in == nil {
		return nil
	}
	out := new(ExternalTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTLSConfig) DeepCopyInto(out *MTLSConfig) {
	*out = *in
	if in.RootCASecretRef != nil {
		in, out := &in.RootCASecretRef, &out.RootCASecretRef
		*out = new(CASecretRef)
		**out = **in
	}
	if in.AssociatedHostnames != nil {
		in, out := &in.AssociatedHostnames, &out.AssociatedHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTLSConfig.
func (in *MTLSConfig) DeepCopy() *MTLSConfig {
	if in == nil {
		return nil
	}
	out := new(MTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginDefaults) DeepCopyInto(out *OriginDefaults) {
	*out = *in
	if in.CAPoolSecretRef != nil {
		in, out := &in.CAPoolSecretRef, &out.CAPoolSecretRef
		*out = new(CAPoolSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginDefaults.
func (in *OriginDefaults) DeepCopy() *OriginDefaults {
	if in == nil {
		return nil
	}
	out := new(OriginDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAncestorStatus) DeepCopyInto(out *PolicyAncestorStatus) {
	*out = *in
	in.AncestorRef.DeepCopyInto(&out.AncestorRef)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAncestorStatus.
func (in *PolicyAncestorStatus) DeepCopy() *PolicyAncestorStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyAncestorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyTargetReference) DeepCopyInto(out *PolicyTargetReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.SectionName != nil {
		in, out := &in.SectionName, &out.SectionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyTargetReference.
func (in *PolicyTargetReference) DeepCopy() *PolicyTargetReference {
	if in == nil {
		return nil
	}
	out := new(PolicyTargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeys) DeepCopyInto(out *SecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeys.
func (in *SecretKeys) DeepCopy() *SecretKeys {
	if in == nil {
		return nil
	}
	out := new(SecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTokenConfig) DeepCopyInto(out *ServiceTokenConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTokenConfig.
func (in *ServiceTokenConfig) DeepCopy() *ServiceTokenConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceTokenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTokenSecretRef) DeepCopyInto(out *ServiceTokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTokenSecretRef.
func (in *ServiceTokenSecretRef) DeepCopy() *ServiceTokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(ServiceTokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelIdentity) DeepCopyInto(out *TunnelIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelIdentity.
func (in *TunnelIdentity) DeepCopy() *TunnelIdentity {
	if in == nil {
		return nil
	}
	out := new(TunnelIdentity)
	in.DeepCopyInto(out)
	return out
}
